name: Go on macOS

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ] 
    

jobs:

  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.22"

      - name: Build amd64
        run: GOARCH=amd64 go build -v ./...

      - name: Build arm64
        run: GOARCH=arm64 go build -v ./...

